### ISSUE TITLE
Combinations of three keys via env.type not working as expected

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#484] opened 2020-09-08 05:53 UTC
As a Sakuli user, I want to use three key combinations with `env.type()` as it was possible in Sakuli 1.x to be able to migrate my checks easier.

In Sakuli 1, a certain window action could be performed by using `env.type(Key.CTRL, Key.SHIFT, Key.NUM7);`. In Sakuli 2, this results in a `/` in the focused field in the window. 

A workaround is
```
await env.keyDown(Key.CTRL)
await env.type(Key.SHIFT, Key.NUM7)
await env.keyUp(Key.CTRL)
```

**Comment by s1hofmann** [comment] 2020-09-08 08:00
I would argue that this is expected behaviour.

[Environment#type](https://sakuli.io/apidoc/sakuli-legacy/interfaces/environment.html#type) accepts a string or [Key](https://sakuli.io/apidoc/sakuli-legacy/classes/key.html) to type as first argument, followed by optional modifier keys.
What happens in `type` is pretty much the exact same behaviour as shown in the workaround snippet.
Optional modifier keys are pressed, followed by the string or `Key` to type.

Applying this to the provided snippet `env.type(Key.CTRL, Key.SHIFT, Key.NUM7)` gives the following order

```
1. keyDown(Key.SHIFT, Key.NUM7);
2. type(Key.CTRL);
3. keyUp(Key.SHIFT, Key.NUM7);
```

resulting in typing `/` (Shift + 7).

Since we're trying to press `Key.NUM7` with optional modifiers `Key.CTRL` and `Key.SHIFT`, arguments have to be reordered:

```js
env.type(Key.NUM7, Key.CTRL, Key.SHIFT)
```

In my opinion, the fact that it worked the other way round in Sakuli 1.x is unexpected behaviour.

**Comment by Marci24h** [comment] 2020-09-08 09:22
@s1hofmann many thanks.

after your explanation i agree with you and it makes sense.
after reordering keys the test is working as expected.

So the issue, that wasn't one can be marked as fixed.

**Closed** 2020-09-08 09:30 UTC
