### ISSUE TITLE
Image recognition fails in case the reference image has a different resolution

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#327] opened 2020-01-30 13:23 UTC
As a Sakuli user, I want Sakuli to match images even if they have a different resolution, so that I am able to use screenshots from my desktop in a environment with different resolutions like a docker container or in a test farm.

@cliffle @s1hofmann @tnobody: I've a test case prepared in a POC repo.

**Comment by s1hofmann** [comment] 2020-07-06 09:19
Duplicate of #406

**Closed by s1hofmann** 2020-07-06 09:19 UTC
