### ISSUE TITLE
How to run the debugger? Webstorm or VsCode

### ISSUE THREAD

**Issue by xela07ax** [sakuli/sakuli#432] opened 2020-06-16 16:51 UTC
![Untitled Project99](https://user-images.githubusercontent.com/16580640/84819795-45d1ad00-b021-11ea-82a1-4d7c38484164.gif)

I am trying to run the debugger in VS Code, but I can’t find anywhere information on how to configure my breakpoints to work.

**How to run the debugger? Webstorm or VsCode**

**Comment by svettwer** [comment] 2020-06-17 07:23
Hi :wave: 

Instead of starting the test execution directly via sakuli, you could use node with the `--inspect` parameter.
`node --inspect node_modules/@sakuli/cli/dist/index run <your-suite>` should do the trick. 

BR
Sven

**Comment by xela07ax** [comment] 2020-06-17 09:36
> Hi 👋
> 
> Instead of starting the test execution directly via sakuli, you could use node with the `--inspect` parameter.
> `node --inspect node_modules/@sakuli/cli/dist/index run <your-suite>` should do the trick.
> 
> BR
> Sven
![what](https://user-images.githubusercontent.com/16580640/84881889-28d7c100-b097-11ea-8d0f-0b2a0774d230.gif)

Thanks, it really works. This is probably an unnecessary remark, the position is 3 lines behind. This does not greatly interfere with the work of course.

**Comment by svettwer** [comment] 2020-06-18 06:59
You're welcome. 
I think this might be the case as we add some imports before we pass the test script to the sandbox for execution. This would at least explain the offset. :thinking:

**Comment by svettwer** [comment] 2020-08-12 10:36
I double checked the import stuff: This is not the root cause.
We'd have to investigate this a little bit further.

**Comment by svettwer** [comment] 2020-08-12 10:43
As the offset issue is different from the "How to run the debugger?"-question, I created #464 as a new ticket and will close this one.

**Closed by svettwer** 2020-08-12 10:43 UTC
