### ISSUE TITLE
integration-tests not working

### ISSUE THREAD

**Issue by cliffle** [sakuli/sakuli#299] opened 2019-12-09 15:52 UTC
**Version**
develop branch

**Short overview**
Typescript errors occur in `integration-tests`

**Detailed error description**

One error occurs in `sakuli/packages/integration-tests/tsconfig.json`
```
Error:TS2688: Cannot find type definition file for '@sakuli/legacy-types'.
Error:TS6053: File '/opt/projects/sakuli/packages/sakuli-rollup-hooks/node_modules/typescript/lib/lib.es2017.d.ts' not found.
```
But the file `lib.es2017.d.ts` exists.

Another error occurs in `sakuli/packages/integration-tests/legacy-suite/test-case/typed-case.ts`. Probably as a result of the previous error.
```
Error:(16, 17) TS2318: Cannot find global type 'Promise'.
Error:(2, 2) TS2697: An async function or method must return a 'Promise'. Make sure you have a declaration for 'Promise' or include 'ES2015' in your `--lib` option.
```

When I try to execute `npx sakuli run legacy-suite`, this happens:
```
(node:15854) UnhandledPromiseRejectionWarning: ReferenceError: jest is not defined
    at Object.<anonymous> (/opt/projects/sakuli/packages/sakuli-cli/dist/commands/run-command.function.spec.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.require (internal/modules/cjs/helpers.js:25:18)
    at /opt/projects/sakuli/packages/sakuli-cli/node_modules/require-directory/index.js:76:17
    at Array.forEach (<anonymous>)
(node:15854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15854) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce error**
After rebuilding with
```bash
lerna exec -- rm -rf dist/ tsconfig.tsbuildinfo
npm run rebuild
```
the errors should appear.

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Code, Config, Dockerfiles etc.)

**Comment by svettwer** [comment] 2019-12-10 07:47
Hi! :wave: 

I briefly checked your issue but was unable to reproduce it. Let' take some time today and have a look at it on your machine.

**Comment by svettwer** [comment] 2019-12-10 08:35
@tnobody We just found out that `NODE_NO_WARNINGS=1` also suppresses node errors from test execution.

**Comment by svettwer** [comment] 2019-12-10 08:37
@tnobody We cannot find the integration test execution in the build pipeline. Are these tests not executed?

**Comment by svettwer** [comment] 2019-12-10 09:00
We've reviewed the release 2.2.0 by creating a new sakuli suite and adding test cases fresh from npmjs.org. This works fine so far.
Nevertheless, the integration test where broken at the time we released 2.2.0.

**Comment by tnobody** [comment] 2019-12-10 09:15
> @tnobody We just found out that `NODE_NO_WARNINGS=1` also suppresses node errors from test execution.

Yes, I also figured out this behavior... When we #284 and #266 we can remove this env var finally

> @tnobody We cannot find the integration test execution in the build pipeline. Are these tests not executed?

Well, this is because they were never finally integrated in the CI and rather used as a playground for local development 🙈 I think we should force to run at least the `npm t` command within this package in CI. We could reuse the container env which is used for the native integration tests.

> We've reviewed the release 2.2.0 by creating a new sakuli suite and adding test cases fresh from npmjs.org. This works fine so far.
Nevertheless, the integration test where broken at the time we released 2.2.0.

It  dont thinkt that they are broken since the last release. I'm pretty sure it has something todo with: #291 . This PR introduced the file `run-command.function.spec.ts` which seems to cause the error:

```bash
(node:15680) UnhandledPromiseRejectionWarning: ReferenceError: jest is not defined
    at Object.<anonymous> (/Users/timkeiner/Projects/consol/TA/sakuli_v2/packages/sakuli-cli/dist/commands/run-command.function.spec.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at Object.require (internal/modules/cjs/helpers.js:20:18)
    at /Users/timkeiner/Projects/consol/TA/sakuli_v2/packages/sakuli-cli/node_modules/require-directory/index.js:76:17
    at Array.forEach (<anonymous>)
(node:15680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Right now I'm completely curios what is going up there. It seems that the `.spec` file is loaded in the runtime and causes n error because `jest` is obviously not defined there... But I can not tell why and where this include/import happens (rightnow)

**Comment by svettwer** [comment] 2019-12-10 09:16
It seems the issue consists of multiple problems.

- lerna linking seems to be broken for the integration test package
- typescript support seems to be broken

**Comment by tnobody** [comment] 2019-12-10 09:17
> Hi! 👋
> 
> I briefly checked your issue but was unable to reproduce it. Lets take some time today and have a look at it on your machine.

Before running `npm run rebuild` you could also try to run `lerna exec -- rm -rf dist/ tsconfig.tsbuildinfo` as described and addressed in #298

**Comment by svettwer** [comment] 2019-12-10 09:18
When we run `npm i` in the integration test package and remove the typescript test, everything runs as expected

**Comment by svettwer** [comment] 2019-12-10 09:20
> > Hi! wave
> > I briefly checked your issue but was unable to reproduce it. Lets take some time today and have a look at it on your machine.
> 
> Before running `npm run rebuild` you could also try to run `lerna exec -- rm -rf dist/ tsconfig.tsbuildinfo` as described and addressed in #298

yeah, but this was not the issue. The build is successful on my machine. The issue showed up while `npx sakuli run legacy-suite`

**Comment by tnobody** [comment] 2019-12-10 09:21
> When we run `npm i` in the integration test package and remove the typescript test, everything runs as expected

When you run `npm i` in integration-test package it will install the sakuli version 2.2.0 from npm which is not broken and should therefore work. That the Typescript test is not running in this scenario might be another issue 🤔

**Comment by tnobody** [comment] 2019-12-10 09:22
> > > Hi! wave
> > > I briefly checked your issue but was unable to reproduce it. Lets take some time today and have a look at it on your machine.
> > 
> > 
> > Before running `npm run rebuild` you could also try to run `lerna exec -- rm -rf dist/ tsconfig.tsbuildinfo` as described and addressed in #298
> 
> yeah, but this was not the issue. The build is successful on my machine. The issue showed up while `npx sakuli run legacy-suite`

Just wanted to ensure that you are working on clean state (cause I already had such issues) :)

**Comment by tnobody** [comment] 2019-12-10 09:27
Ok I'm pretty sure that I have identified the problem and found a solution:

The problem ist that we use `.commandDir` from `yargs` which dynamically loads all files from a given directory (and tries to handle them as a command-object). When adding the spec file to the command folder it also loads this file dynamically and fails because some references to jest (which are automatically injected in a test jest run but obviously not in Sakuli)

**Comment by svettwer** [comment] 2019-12-10 09:29
> > When we run `npm i` in the integration test package and remove the typescript test, everything runs as expected
> 
> When you run `npm i` in integration-test package it will install the sakuli version 2.2.0 from npm which is not broken and should therefore work. That the Typescript test is not running in this scenario might be another issue

Yes, and I'm very happy that the release is **not** broken. =)

**Comment by svettwer** [comment] 2019-12-10 09:31
> Ok I'm pretty sure that I have identified the problem and found a solution:
> 
> The problem ist that we use `.commandDir` from `yargs` which dynamically loads all files from a given directory (and tries to handle them as a command-object). When adding the spec file to the command folder it also loads this file dynamically and fails because some references to jest (which are automatically injected in a test jest run but obviously not in Sakuli)

okay... is that an expected/desired `yargs` behavior? :sweat_smile:

**Closed** 2019-12-10 11:16 UTC
